# Generated by Django 5.0.3 on 2024-05-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='manga_name',
            new_name='name',
        ),
    ]
