# Generated by Django 5.0.3 on 2024-05-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.IntegerField(),
        ),
    ]
